# Generated by Django 5.2.8 on 2025-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('LIBRARIAN', 'Librarian')], max_length=10),
        ),
    ]
